# -*- coding: utf-8 -*-
"""Streamlit Stuff

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4TSe1jwgmOWuJyP47widXH8Vb9TerCR
"""

import pandas as pd
import altair as alt
import streamlit as st

data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

st.set_page_config(page_title="Titanic", initial_sidebar_state = 'collapsed', layout='wide')

#Can we scroll? Controls
#Input boxes/Buttons
#What does your layout look like?

#Where is my daata [Github, Streamlit, Browser]
#Sessions as part of interactivity
#streamlit layouts and containers, look it up

col1, col2, col3 = st.columns(3)

data.info()

chart1 = alt.Chart(data).mark_circle(size = 100).encode(
    x = 'Age',
    y = 'Fare',
    tooltip = ['Name', 'Survived']
)

chart2 = alt.Chart(data).mark_area().encode(
    alt.X('Fare'),
    alt.Y('Age')
)
#with st.sidebar:
  #
with col1:
  st.altair_chart(chart1, use_container_width = True)
with col2:
    st.altair_chart(chart2, use_container_width = True)
with col3:
    st.header("This is col 3")

data.sample(10)

#Make a sidebar

#Make three charts
